server:
  port: 8334

spring:
  datasource: # h2数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    ##  Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 10
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

nacos:
  discovery:
    server-addr: 127.0.0.1:8848
  config:
    server-addr: 127.0.0.1:8848

dubbo:
  registry:
    address: nacos://${nacos.discovery.server-addr}
  application:
    name: dubbo-provider-second
    qosPort: 33333
    qosEnable: true
    qosAcceptForeignIp: false
  #scan:
  #  base-packages: com.xx.service
  protocol:
    name: dubbo
    port: 20881

mybatis-plus:
  # ---------------------------------------/模块/--------.xml
  mapper-locations: classpath:/com/egg/core/*/mapper/xml/*Mapper.xml